# Generated by Django 3.1.7 on 2021-04-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20210405_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='clocksystem',
            name='minutes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clocksystem',
            name='hours_worked',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clocksystem',
            name='location',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='clocksystem',
            name='role',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
