# Generated by Django 3.1.7 on 2021-07-06 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20210408_0138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('last_name', 'first_name', 'is_active')},
        ),
    ]
