# Generated by Django 3.1.5 on 2021-07-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20210711_0425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clocksystem',
            options={'ordering': ('date_in', 'date_out', 'clocked_in_at', 'clocked_out_at', 'employee', 'location', 'role', 'hours_worked', 'minutes_worked', 'seconds_worked', 'in_comment', 'out_comment')},
        ),
        migrations.RenameField(
            model_name='clocksystem',
            old_name='date_worked',
            new_name='date_in',
        ),
        migrations.AddField(
            model_name='clocksystem',
            name='date_out',
            field=models.DateField(null=True),
        ),
    ]
