# Generated by Django 3.1.5 on 2021-07-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20210711_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clocksystem',
            options={'ordering': ('date_in', 'date_out', 'clocked_in_at', 'clocked_out_at', 'employee', 'location', 'role', 'time_worked', 'in_comment', 'out_comment')},
        ),
        migrations.RenameField(
            model_name='clocksystem',
            old_name='hours_worked',
            new_name='time_worked',
        ),
        migrations.RemoveField(
            model_name='clocksystem',
            name='minutes_worked',
        ),
        migrations.RemoveField(
            model_name='clocksystem',
            name='seconds_worked',
        ),
    ]
