# Generated by Django 3.1.5 on 2021-07-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20210711_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clocksystem',
            name='time_worked',
            field=models.TimeField(null=True),
        ),
    ]
