# Generated by Django 3.1.5 on 2021-07-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20210711_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clocksystem',
            name='time_worked',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
