# Generated by Django 3.1.5 on 2021-07-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20210712_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clocksystem',
            name='in_comment',
            field=models.TextField(default='**None', null=True),
        ),
        migrations.AlterField(
            model_name='clocksystem',
            name='out_comment',
            field=models.TextField(default='**None', null=True),
        ),
    ]
