# Generated by Django 3.1.5 on 2021-07-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_auto_20210718_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clocksystem',
            name='location',
            field=models.CharField(default='**Not Provided', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='clocksystem',
            name='role',
            field=models.CharField(default='**Not Provided', max_length=80, null=True),
        ),
    ]
