# Generated by Django 3.1.5 on 2021-07-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_auto_20210719_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clocksystem',
            name='time_worked',
            field=models.CharField(default='00:00:00', max_length=255),
        ),
    ]
