# Generated by Django 3.1.5 on 2021-07-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_auto_20210720_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clocksystem',
            name='time_worked',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
