# Generated by Django 3.1.6 on 2021-07-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_auto_20210720_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clocksystem',
            name='in_comment',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='clocksystem',
            name='location',
            field=models.CharField(default=' ', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='clocksystem',
            name='out_comment',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='clocksystem',
            name='role',
            field=models.CharField(default=' ', max_length=80, null=True),
        ),
    ]
