# Generated by Django 3.1.6 on 2021-07-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_auto_20210721_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='Not Provide', max_length=255),
        ),
        migrations.AlterField(
            model_name='clocksystem',
            name='in_comment',
            field=models.TextField(default='None', null=True),
        ),
        migrations.AlterField(
            model_name='clocksystem',
            name='location',
            field=models.CharField(default='None', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='clocksystem',
            name='out_comment',
            field=models.TextField(default='None', null=True),
        ),
        migrations.AlterField(
            model_name='clocksystem',
            name='role',
            field=models.CharField(default='None', max_length=80, null=True),
        ),
    ]
